--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.78.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 05/11/2017 23:31:28
-- Server version: 5.7.20-log
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE ywp2_dev;

--
-- Definition for table category
--
DROP TABLE IF EXISTS category;
CREATE TABLE category (
  name VARCHAR(50) NOT NULL,
  priority INT(11) DEFAULT NULL,
  parent_category INT(11) DEFAULT NULL,
  id INT(11) NOT NULL AUTO_INCREMENT,
  created_at DATE DEFAULT NULL,
  updated_at DATE DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX name (name)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
AVG_ROW_LENGTH = 5461
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table job
--
DROP TABLE IF EXISTS job;
CREATE TABLE job (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  metadataJson VARCHAR(255) DEFAULT NULL,
  callback_url VARCHAR(255) DEFAULT NULL,
  submit_time DATE DEFAULT NULL,
  status ENUM('NEW','EXECUTING','PRIORITIZED','FAILED','RETRYING','SUCCESSFUL') NOT NULL,
  scheduled_time DATE DEFAULT NULL,
  completion_time DATE DEFAULT NULL,
  retry_count INT(11) DEFAULT NULL,
  category INT(11) DEFAULT NULL,
  created_at DATE DEFAULT NULL,
  updated_at DATE DEFAULT NULL,
  metadata_json VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table role
--
DROP TABLE IF EXISTS role;
CREATE TABLE role (
  role_id INT(11) NOT NULL AUTO_INCREMENT,
  role VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (role_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table user
--
DROP TABLE IF EXISTS user;
CREATE TABLE user (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  active INT(11) DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  displayName VARCHAR(255) NOT NULL,
  encryptedPassword VARCHAR(255) NOT NULL,
  iv VARCHAR(255) NOT NULL,
  salt VARCHAR(255) NOT NULL,
  keySize INT(11) NOT NULL,
  iterations INT(11) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB
AUTO_INCREMENT = 4
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

--
-- Definition for table user_role
--
DROP TABLE IF EXISTS user_role;
CREATE TABLE user_role (
  user_id INT(11) NOT NULL,
  role_id INT(11) NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT FK859n2jvi8ivhui0rl0esws6o FOREIGN KEY (user_id)
    REFERENCES user(user_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FKa68196081fvovjhkek5m97n3y FOREIGN KEY (role_id)
    REFERENCES role(role_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table category
--
INSERT INTO category VALUES
('cat1', 1, NULL, 1, '2017-11-04', '2017-11-04'),
('cat2', 2, NULL, 2, '2017-11-04', '2017-11-04'),
('cat3', 3, NULL, 3, '2017-11-04', '2017-11-04');

-- 
-- Dumping data for table job
--

-- Table ywp2_dev.job does not contain any data (it is empty)

-- 
-- Dumping data for table role
--
INSERT INTO role VALUES
(1, 'ADMIN');

-- 
-- Dumping data for table user
--

-- Table ywp2_dev.user does not contain any data (it is empty)

-- 
-- Dumping data for table user_role
--

-- Table ywp2_dev.user_role does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;